/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Создайте столько боковых панелей, сколько вы хотите.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // По умолчанию Docusaurus генерирует боковую панель из структуры папки Docs
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Но вы можете создать боковую панель вручную
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
